name: Tests - 

on:
  push:


jobs:
  test-:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Build image
        run: |
          docker build -t p .
      - 
        name: Test
        run: |
          docker run --rm p crystal spec